apiVersion: v1
kind: Secret
metadata:
  name: ipe-database-credentials
  labels:
    {{- include "ipe.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ template "ipe.postgres-dsn" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: ipe-service-keys
  labels:
    {{- include "ipe.labels" . | nindent 4 }}
type: Opaque
stringData:
  connector-hmac-key: {{ randAlphaNum 32 | quote }}
  internal-api-key: {{ randAlphaNum 64 | quote }}
