/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ipe: {
          primary: 'var(--color-primary)',
          'primary-hover': 'var(--color-primary-hover)',
          secondary: 'var(--color-secondary)',
          accent: 'var(--color-accent)',
          danger: 'var(--color-danger)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          navy: 'var(--color-navy)',
          'navy-elevated': 'var(--color-navy-elevated)',
          surface: 'var(--color-surface)',
          'surface-alt': 'var(--color-surface-alt)',
          'surface-card': 'var(--color-surface-card)',
          border: 'var(--color-border)',
          'border-strong': 'var(--color-border-strong)',
          text: 'var(--color-text)',
          'text-muted': 'var(--color-text-muted)',
          'text-inverse': 'var(--color-text-inverse)',
        },
        score: {
          excellent: 'var(--score-excellent)',
          good: 'var(--score-good)',
          warning: 'var(--score-warning)',
          risk: 'var(--score-risk)',
          critical: 'var(--score-critical)',
        },
        feasibility: {
          excellent: 'var(--feasibility-excellent)',
          good: 'var(--feasibility-good)',
          warning: 'var(--feasibility-warning)',
          risk: 'var(--feasibility-risk)',
          critical: 'var(--feasibility-critical)',
        },
        constraint: {
          material: 'var(--constraint-material)',
          capacity: 'var(--constraint-capacity)',
          labor: 'var(--constraint-labor)',
        },
        ai: {
          DEFAULT: 'var(--color-ai)',
          muted: 'var(--color-ai-muted)',
          foreground: 'var(--color-ai-foreground)',
        },
        'ipe-green': '#10B981',
        'ipe-amber': '#F59E0B',
        'ipe-red': '#EF4444',
        'ipe-blue': '#3B82F6',
        'ipe-purple': '#8B5CF6',
        'ipe-navy': '#0F172A',
        'ipe-navy-light': '#1E293B',
        'ipe-slate': '#F8FAFC',
        'ipe-green-bg': '#DCFCE7',
        'ipe-amber-bg': '#FEF3C7',
        'ipe-red-bg': '#FEE2E2',
        'ipe-blue-bg': '#DBEAFE',
        'ipe-purple-bg': '#EDE9FE',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Segoe UI', 'system-ui', 'sans-serif'],
        arabic: ['Cairo', 'IBM Plex Sans Arabic', 'Segoe UI', 'Tahoma', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      spacing: {
        rail: 'var(--rail-width)',
        'domain-side': 'var(--domain-sidebar-width)',
        header: 'var(--header-height)',
      },
      maxWidth: {
        content: '1440px',
      },
    },
  },
  plugins: [],
};
