apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ipe-staging

resources:
  - ../../base/namespace.yml
  - ../../base/configmap.yml
  - ../../base/secrets.yml
  - ../../services/dpe-svc.yml
  - ../../services/mat-svc.yml
  - ../../services/cap-svc.yml
  - ../../services/fea-svc.yml
  - ../../services/res-svc.yml
  - ../../services/del-svc.yml
  - ../../services/nlp-svc.yml
  - ../../services/web.yml

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
