apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ipe-platform-mtls
  namespace: ipe-platform
spec:
  host: "*.ipe-platform.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL